defaultAirflowTag: "2.3.0"
airflowVersion: "2.3.0"
executor: "KubernetesExecutor"
env:
  - name: AIRFLOW__LOGGING__REMOTE_LOGGING
    value: 'True'
  - name: AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER
    value: 's3://aws-logs-341567884088-us-east-1/logs/' ## Endereço uri do da sua pasta onde vão ficar os logs do Airflow
  - name: AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID
    value: 'my_aws'
webserver:
  defaultUser:
    enabled: true
    role: Admin
    username: seu.usuario
    email: seu-e-mail
    firstName: primeiroNome
    lastName: UltimoNome
    password: admin
  service:
    type: LoadBalancer

redis:
  enabled: false

dags:
  gitSync:
    enabled: true
    repo: https://github.com/MiriamAlmeida/puc_minas_data_pipelines.git # no seu repositório faz copie o link
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags" ## COLOQUE O NOME DA PASTA ONDE ESTÃO AS DAGS
    wait: 60
    containerName: git-sync
    uid: 65533
    securityContext: {}
    extraVolumeMounts: []
    env: []
    resources: {}